FROM golang:1.27.1 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
# Build statically linked binary
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o pii-shield ./cmd/cleaner

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /app/pii-shield .
USER 65532:65532

ENTRYPOINT ["/pii-shield"]
