apiVersion: v2
name: pii-shield
description: A Helm chart for deploying PII-Shield as a scratch-compatible logging sidecar
type: application
version: 2.2.1
appVersion: "2.2.1"

annotations:
  artifacthub.io/official: "true"
home: https://github.com/pii-shield/pii-shield
sources:
  - https://github.com/pii-shield/pii-shield
keywords:
  - security
  - observability
  - pii
  - compliance
maintainers:
  - name: aragossa
    email: ilya.ploskovitov@pii-shield.com
