apiVersion: v2
name: pii-shield-operator
description: A Kubernetes Operator for automatic PII (Personally Identifiable Information) masking in application logs using native distroless sidecars.

type: application

version: 2.2.1

appVersion: "2.2.1"

home: https://github.com/pii-shield/pii-shield
sources:
  - https://github.com/pii-shield/pii-shield
maintainers:
  - name: aragossa
    email: ilya.ploskovitov@pii-shield.com

annotations:
  artifacthub.io/category: security
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/pii-shield/pii-shield/tree/main/operator
    - name: GitHub
      url: https://github.com/pii-shield/pii-shield
